# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bioreactor.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MainFrame = QtWidgets.QFrame(self.centralwidget)
        self.MainFrame.setStyleSheet("border-image: url(:/background.png/background.png);")
        self.MainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MainFrame.setObjectName("MainFrame")
        self.frame_2 = QtWidgets.QFrame(self.MainFrame)
        self.frame_2.setGeometry(QtCore.QRect(182, 15, 604, 570))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 570))
        self.frame_2.setStyleSheet("border-image: url(:/background.png/Main_frame.png);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.ButtonFrame = QtWidgets.QFrame(self.MainFrame)
        self.ButtonFrame.setGeometry(QtCore.QRect(10, 20, 161, 291))
        self.ButtonFrame.setMaximumSize(QtCore.QSize(16777215, 571))
        self.ButtonFrame.setAutoFillBackground(False)
        self.ButtonFrame.setStyleSheet("QFrame {\n"
"    border:none\n"
"}")
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.overview_btn = QtWidgets.QPushButton(self.ButtonFrame)
        self.overview_btn.setGeometry(QtCore.QRect(10, 42, 143, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.overview_btn.setFont(font)
        self.overview_btn.setStyleSheet("border-image: url(:/background.png/Button.png);\n"
"color: rgb(33, 170, 223);")
        self.overview_btn.setFlat(False)
        self.overview_btn.setObjectName("overview_btn")
        self.heating_btn = QtWidgets.QPushButton(self.ButtonFrame)
        self.heating_btn.setGeometry(QtCore.QRect(10, 101, 143, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.heating_btn.setFont(font)
        self.heating_btn.setStyleSheet("border-image: url(:/background.png/Button.png);\n"
"color: rgb(33, 170, 223);")
        self.heating_btn.setFlat(False)
        self.heating_btn.setObjectName("heating_btn")
        self.stirring_btn = QtWidgets.QPushButton(self.ButtonFrame)
        self.stirring_btn.setGeometry(QtCore.QRect(10, 160, 143, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.stirring_btn.setFont(font)
        self.stirring_btn.setStyleSheet("border-image: url(:/background.png/Button.png);\n"
"color: rgb(33, 170, 223);")
        self.stirring_btn.setFlat(False)
        self.stirring_btn.setObjectName("stirring_btn")
        self.ph_btn = QtWidgets.QPushButton(self.ButtonFrame)
        self.ph_btn.setGeometry(QtCore.QRect(10, 219, 143, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.ph_btn.setFont(font)
        self.ph_btn.setStyleSheet("border-image: url(:/background.png/Button.png);\n"
"color: rgb(33, 170, 223);")
        self.ph_btn.setFlat(False)
        self.ph_btn.setObjectName("ph_btn")
        self.quit_btn = QtWidgets.QPushButton(self.MainFrame)
        self.quit_btn.setGeometry(QtCore.QRect(16, 11, 20, 20))
        self.quit_btn.setStyleSheet("QPushButton {\n"
"    border-image: url(:/background.png/quit_btn_1.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-image: url(:/background.png/quit_btn.png);\n"
"}")
        self.quit_btn.setText("")
        self.quit_btn.setObjectName("quit_btn")
        self.label = QtWidgets.QLabel(self.MainFrame)
        self.label.setGeometry(QtCore.QRect(10, 570, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(24, 153, 213)")
        self.label.setObjectName("label")
        self.ButtonFrame.raise_()
        self.frame_2.raise_()
        self.quit_btn.raise_()
        self.label.raise_()
        self.verticalLayout.addWidget(self.MainFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.overview_btn.setText(_translate("MainWindow", "Overview"))
        self.heating_btn.setText(_translate("MainWindow", "Heating"))
        self.stirring_btn.setText(_translate("MainWindow", "Stirring"))
        self.ph_btn.setText(_translate("MainWindow", "PH"))
        self.label.setText(_translate("MainWindow", "Created by UCL-CSEEE23"))
    
    
        
   


import background_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
